# Generated by Django 5.1.7 on 2025-03-14 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_development', models.BooleanField(default=False)),
                ('employment_path_community', models.BooleanField(default=False)),
                ('employment_path_solo', models.BooleanField(default=False)),
                ('job_coaching_vr', models.BooleanField(default=False)),
                ('job_coaching_odds', models.BooleanField(default=False)),
                ('career_exploration', models.BooleanField(default=False)),
                ('targeted_vocational_assessments', models.BooleanField(default=False)),
                ('community_based_work_assessments', models.BooleanField(default=False)),
                ('job_retention', models.BooleanField(default=False)),
                ('discovery', models.BooleanField(default=False)),
                ('dsa_facility', models.BooleanField(default=False)),
                ('dsa_community', models.BooleanField(default=False)),
                ('adl_iadl', models.BooleanField(default=False)),
                ('accepting_referrals', models.BooleanField(default=False)),
                ('referral_services', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency_detail', to='myapp.profile')),
            ],
        ),
    ]
