# Generated by Django 5.1.7 on 2025-03-14 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_agencydetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agencydetail',
            name='services_provided',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='agencydetail',
            name='agency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency_detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agencydetail',
            name='referral_services',
            field=models.JSONField(default=list),
        ),
    ]
