# Generated by Django 5.1.7 on 2025-03-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_agencydetail_services_provided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencydetail',
            name='referral_limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
