# Generated by Django 5.1.7 on 2025-03-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_agencydetail_referral_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencydetail',
            name='referral_limit',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
