# Generated by Django 5.1.7 on 2025-03-16 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_agencydetail_referral_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencydetail',
            name='services_provided',
        ),
        migrations.AlterField(
            model_name='agencydetail',
            name='referral_limit',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
