# Generated by Django 5.1.7 on 2025-03-16 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_agencydetail_services_provided_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencydetail',
            name='referral_limit',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
