# Generated by Django 5.1.7 on 2025-03-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_agencydetail_referral_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agency_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
