# Generated by Django 5.1.7 on 2025-03-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_profile_agency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencydetail',
            name='community_living_services',
            field=models.BooleanField(default=False),
        ),
    ]
