# Generated by Django 5.1.7 on 2025-03-20 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_agencydetail_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('job_development', 'Job Development'), ('employment_path_community', 'Employment Path-Community'), ('employment_path_solo', 'Employment Path Solo'), ('job_coaching_vr', 'Job Coaching (VR)'), ('job_coaching_odds', 'Job Coaching (ODDS)'), ('career_exploration', 'Career Exploration'), ('targeted_vocational_assessments', 'Targeted Vocational Assessments'), ('community_based_work_assessments', 'Community Based Work Assessments'), ('job_retention', 'Job Retention'), ('discovery', 'Discovery'), ('dsa_facility', 'DSA (Facility)'), ('dsa_community', 'DSA (Community)'), ('adl_iadl', 'ADL/IADL'), ('community_living_services', 'Community Living Services')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='agencydetail',
            name='referral_services',
        ),
        migrations.AlterField(
            model_name='agencydetail',
            name='referral_limit',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='agencydetail',
            name='services_provided',
            field=models.ManyToManyField(blank=True, to='myapp.service'),
        ),
    ]
