# Generated by Django 5.1.7 on 2025-03-20 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0012_service_remove_agencydetail_referral_services_and_more'),
    ]

    operations = [
        # No operations; this is a placeholder migration to maintain the chain
    ]
