# Generated by Django 5.1.7 on 2025-03-20 19:33

from django.db import migrations


def populate_services(apps, schema_editor):
    # Get the Service model
    Service = apps.get_model('myapp', 'Service')

    SERVICE_CHOICES = [
        ('job_development', 'Job Development'),
        ('employment_path_community', 'Employment Path-Community'),
        ('employment_path_solo', 'Employment Path Solo'),
        ('job_coaching_vr', 'Job Coaching (VR)'),
        ('job_coaching_odds', 'Job Coaching (ODDS)'),
        ('career_exploration', 'Career Exploration'),
        ('targeted_vocational_assessments', 'Targeted Vocational Assessments'),
        ('community_based_work_assessments', 'Community Based Work Assessments'),
        ('job_retention', 'Job Retention'),
        ('discovery', 'Discovery'),
        ('dsa_facility', 'DSA (Facility)'),
        ('dsa_community', 'DSA (Community)'),
        ('adl_iadl', 'ADL/IADL'),
        ('community_living_services', 'Community Living Services'),
    ]

    for key, name in SERVICE_CHOICES:
        Service.objects.get_or_create(key=key, name=name)


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0012_service_remove_agencydetail_referral_services_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_services),
    ]
