# Generated by Django 5.1.7 on 2025-03-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20250320_1239'),
    ]

    operations = [
    ]
