# Generated by Django 5.1.7 on 2025-03-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20250320_1233'),
        ('myapp', '0015_auto_20250320_1519'),
    ]

    operations = [
    ]
