# Generated by Django 5.1.7 on 2025-03-29 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('provider', 'Provider Agency'), ('coordinator', 'Service Coordinator / Personal Agent'), ('owner', 'Agency Owner')], max_length=20)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('contact_first_name', models.CharField(max_length=50)),
                ('contact_last_name', models.CharField(max_length=50)),
                ('referral_status', models.CharField(choices=[('accepting', 'Accepting Referrals'), ('not_accepting', 'Not Accepting Referrals')], default='not_accepting', max_length=20)),
                ('agency_name', models.CharField(blank=True, max_length=100)),
                ('agency_phone', models.CharField(blank=True, max_length=20)),
                ('agency_email', models.EmailField(blank=True, max_length=254)),
                ('residential_referrals', models.PositiveIntegerField(default=0)),
                ('afc_referrals', models.PositiveIntegerField(default=0)),
                ('behavior_referrals', models.PositiveIntegerField(default=0)),
                ('dsa_facility_referrals', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
