# Generated by Django 5.1.7 on 2025-03-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_county_remove_userprofile_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='agency_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
