# Generated by Django 5.1.7 on 2025-03-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_alter_userprofile_agency_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='agency_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='agency_phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
