# Generated by Django 5.1.7 on 2025-04-01 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_remove_userprofile_vocational_assessments_referrals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='adl_iadl_referral_count',
            new_name='adl_iadl_referrals_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='afc_referral_count',
            new_name='afc_referrals_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='behavior_referral_count',
            new_name='behavior_referrals_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='career_exploration_referral_count',
            new_name='career_exploration_referrals_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='dsa_community_referral_count',
            new_name='dsa_community_referrals_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='dsa_community_solo_referral_count',
            new_name='dsa_community_solo_referrals_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='dsa_facility_referral_count',
            new_name='dsa_facility_referrals_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='employment_path_community_referral_count',
            new_name='employment_path_community_referrals_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='employment_path_community_solo_referral_count',
            new_name='employment_path_community_solo_referrals_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='job_coaching_referral_count',
            new_name='job_coaching_referrals_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='job_development_referral_count',
            new_name='job_development_referrals_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='job_search_assistance_referral_count',
            new_name='job_search_assistance_referrals_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='residential_referral_count',
            new_name='residential_referrals_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='vocational_rehabilitation_referral_count',
            new_name='vocational_rehabilitation_referrals_count',
        ),
    ]
