# Generated by Django 5.1.7 on 2025-04-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_rename_adl_iadl_referral_count_userprofile_adl_iadl_referrals_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
