# Generated by Django 5.1.7 on 2025-04-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
