# Generated by Django 5.1.7 on 2025-04-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_userprofile_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
