# Generated by Django 5.1.7 on 2025-04-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_userprofile_website_alter_userprofile_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('provider', 'Provider Agency'), ('coordinator', 'State/County Entity')], max_length=20),
        ),
    ]
