# Generated by Django 5.1.7 on 2025-04-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('odds', 'ODDS'), ('vr', 'VR')], help_text='Applicable only to State/County Entities', max_length=10, null=True),
        ),
    ]
