# Generated by Django 5.1.7 on 2025-04-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_userprofile_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
