# Generated by Django 5.1.7 on 2025-04-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0017_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, choices=[('OR', 'Oregon'), ('WA', 'Washington'), ('CA', 'California')], max_length=2, null=True),
        ),
    ]
