# Generated by Django 5.1.7 on 2025-04-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0018_userprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agency_name',
            field=models.CharField(blank=True, help_text='Used by provider agencies to store their official name', max_length=255, null=True),
        ),
    ]
