# Generated by Django 5.1.7 on 2025-04-11 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0019_userprofile_agency_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('post_type', models.CharField(choices=[('event', 'Event'), ('placement', 'Job Placement'), ('employer', 'Employer Hiring')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=255)),
                ('employer_website', models.URLField(blank=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.county')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
